agent_class: 'rlberry.agents.torch.A2CAgent'
init_kwargs:
    learning_rate: 0.0007
    optimizer_type: 'RMS_PROP'
    batch_size: 64
    eval_interval: 1000
n_fit: 1
fit_kwargs:
    fit_budget: 1_000_000