agent_class: 'rlberry.agents.torch.A2CAgent'
init_kwargs:
    learning_rate: 0.0007
    optimizer_type: 'RMS_PROP'
    batch_size: 5
    policy_net_fn: 'rlberry.agents.torch.utils.training.model_factory_from_env'
    policy_net_kwargs:
      type: 'MultiLayerPerceptron'
      layer_sizes: [256]
      reshape: False
      is_policy: True
    value_net_fn: 'rlberry.agents.torch.utils.training.model_factory_from_env'
    value_net_kwargs:
      type: "MultiLayerPerceptron"
      layer_sizes": 
        - 512
      reshape: False
      out_size: 1
    horizon: 500
    entr_coef: 0.01
eval_kwargs:
    eval_horizon: 200
n_fit: 1
fit_kwargs:
    fit_budget: 1000
agent_name: "A2C rlberry agent for Acrobot"

