description: 'Acrobot by rlberry'
seed: 23
train_env: './configs/envs/acrobot.yaml'
eval_env: './configs/envs/acrobot.yaml'
agents:
    - './configs/a2c/a2c_acrobot.yaml' 
    - './configs/dqn/dqn_acrobot.yaml'